### ISSUE TITLE
页面布局

### ISSUE THREAD

**Issue by lewenweijia** [lewenweijia/notes#45]
**前端布局发展史**
`表格布局(table) -> 定位(position) -> 浮动布局(float) -> 弹性盒布局(flex) -> 栅格布局(grid)`

**Comment by lewenweijia** [comment]
**最便捷的垂直居中**
```css
.container { display: flex; }
.item { margin: auto }
```
